# Generated by Django 4.1.5 on 2023-02-04 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('cuerpo', models.CharField(max_length=1000, null=True)),
                ('fecha_publicacion', models.DateField(null=True)),
                ('autor', models.CharField(max_length=64)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenesreview')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
