# Generated by Django 4.1.5 on 2023-02-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_review_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='fecha',
        ),
        migrations.AddField(
            model_name='review',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cuerpo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
        migrations.AlterField(
            model_name='review',
            name='subtitulo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='titulo',
            field=models.CharField(max_length=256),
        ),
    ]
